name: prometheus-swift-account-exporter
version: 0.0.8
summary: Exposes high level OpenStack Swift metrics to Prometheus.
description: |
  Exposes high level OpenStack Swift metrics to Prometheus

confinement: strict
grade: stable
apps:
  prometheus-swift-account-exporter:
    command: 'bin/prometheus-swift-account-exporter.wrapper'
    plugs: [network-bind, network]
    daemon: simple
parts:
  prometheus-swift-account-exporter:
    plugin: python
    python-version: python2
    source: .
    stage-packages:
      - libdb5.3
  example-config:
    plugin: dump
    source: .
    organize:
      prometheus-swift-account-exporter.yaml: etc/prometheus/prometheus-swift-account-exporter.yaml.example
    prime:
      - etc/prometheus/prometheus-swift-account-exporter.yaml.example
  snap-wrappers:
    plugin: dump
    source: .
    organize:
      snap_cmd_wrapper: bin/prometheus-swift-account-exporter.wrapper
    prime:
      - bin/prometheus-swift-account-exporter.wrapper
